### PR TITLE
[PasscodeLock] Added the ablility to change code length.

### PR DESCRIPTION
**Pull request by 253ping**
Added the option to change the code length to 4, 6 or unlimited digits.

Preview:
passcode-test

### CODE REVIEW

**Comment by 253ping** [comment]
Personally i would set the limit to 14 or 15 so the dots still fit.
15 digits would look something like this:
dots
 The ok-button could be moved under the 0 while editing the code and to the position of the arrow while in normal mode.

**Comment by arg0NNY** [comment]
15 is ok.

I agree with you on OK button, but I think in normal mode the OK button should be on the right side (where the Backspace is currently located), while Backspace on the left.
Also would be cool if it wasn't just a text but an checkmark icon.

**Comment by arg0NNY** [comment]
I've taken this icons from the Google Fonts btw.

**Comment by 253ping** [comment]
I've added the 15-Digit limit and also added an animation if the digit limit is reached.
limit

**Comment by arg0NNY** [comment]
Looks cool.

**Comment by 253ping** [comment]
enter-key mp4

**Comment by arg0NNY** [comment]
Good, but I think this icon will look a lot better since currently it is too thin compared to anything else

**Comment by 253ping** [comment]
Change the icon the Check Circle.
Also added back the dot animations.
https://user-images.githubusercontent.com/66729859/172696104-722e0807-f9a9-4b2c-a9ac-fcab8ec60bf5.mp4

**Comment by 253ping** [comment]
Whoops... Accidentally uploaded the mp4...
passcode mp4

**Comment by arg0NNY** [comment]
Please fill out the 1.2.0 version and the changelog and I will merger it

**Comment by 253ping** [comment]
Updated the changelog and READMEs.
Also prevented the enter-button from showing when a code with a defined length is used.

**Pull request merged**
