### PR TITLE
Replace `useStateFromStores` to `useSyncExternalStore`

### PR DESCRIPTION
**Pull request by Leah96xxx**
Fixes issue #92

### CODE REVIEW

**Comment by Leah96xxx** [comment]
Ok, upon testing it looks like this is only a partial fix. BetterGuildTooltip and InMyVoice don't give any errors, but it looks like BetterChannelList is now complaining about `'ChannelItemIcon' of 'ChannelItem'`, and ChannelsPreview is complaining about `'default' of 'WebpackModules.getByProps(...)'`

**Comment by Leah96xxx** [comment]
Ok, looking into this, it seems that trying to troubleshoot this is well outside my experience level. Gonna have to hand this back over to the pros, sorry. I jumped in over my head again

**Comment by sirlupusdev** [comment]
No worries, everyone's gotta start somewhere.

**Comment by arg0NNY** [comment]
`useStateFromStores` is actually still there, as all the other modules which were exported before this Discord release, it's just a lot of them got their export names mangled, as with `useStateFromStores`, which now can be received using this getter, which uses searching by string in the module's source code instead of its name:
```js
BdApi.Webpack.getModule(BdApi.Webpack.Filters.byStrings('useStateFromStores'), { searchExports: true })
```

> Yep, turns out `useStateFromStores` contains `"useStateFromStores"` string inside its source code, cool :)
> If only it was as simple as that with all the other modules...

**Comment by arg0NNY** [comment]
Huge thanks for your attempt at contribution! But I have to close this PR since it doesn't fix the plugin completely and the fix has been already pushed by me.

**Pull request closed without merging**
